Increment 7
PanovAlexey/url_carver pull request #8
Opened 2022-02-23 15:36 UTC by PanovAlexey

2022-02-23 15:42 UTC, PanovAlexey commented
@Barugoo Кода получилось не так уж мало, поэтому, для удобства сделал еще отдельные мерж реквесты по каждому инкременту (особенно актуально, т.к. часть коммитов еще и рефакторинг захватили):
https://github.com/PanovAlexey/url_carver/pulls

2022-02-28 16:46 UTC, Barugoo commented on cmd/shortener/main.go
> +	fileStorageRepository, error := repositories.GetFileStorageRepository(config)
`error` - это ключевое слово, лучше не использовать ключевые слова в именовании сущностей
Давай лучше сделаем `err`

2022-02-28 16:47 UTC, Barugoo commented on cmd/shortener/main.go
> +		log.Printf("error creating file repository by config:" + error.Error())
Нужно стопать процесс, если с заданной конфигурацией что-то не завелось: ты можешь и не заметить этот лог, а сервис будет работать как ни в чем не бывало, пока ты думаешь шо у тебя данные пишутся в файл

2022-02-28 16:48 UTC, Barugoo commented on cmd/shortener/main.go
> +	URLMemoryService.LoadURLs(URLStorageService.GetURLCollectionFromStorage())
Давай уберем URL из названия всех компонентов сервиса (URLStorage, URLMemory, URLShortening), мы же итак знаем, что это сервис для сокращения урлов)

2022-02-28 16:55 UTC, Barugoo commented on config/config.go
> +func getFlags() (string, string, string) {
Было бы круто, если бы разработчик смог понять что есть что в возвращаемых значениях не залазяя в тело функции - чем больше информации в сигнатуре, тем лучше. В Go можно именовать возвращаемые значения, повышая читаемость кода:
```go
func getFlags() (serverAddr string, baseURL string, fileStoragePath string) {
```

2022-02-28 16:58 UTC, Barugoo commented on config/config.go
> +func getFlags() (string, string, string) {
Я бы вытащил логику этой функции и целиком бы ее вставил в то место, где она вызывается:
```go
func initConfigByFlag(config *Config) *Config {
	if flag.Parsed() {
		fmt.Println("Error occurred. Re-initializing the config")
		return "", "", ""
	}

        serverAddress := flag.String("a", "", "SERVER_ADDRESS")
	baseURL := flag.String("b", "", "BASE_URL")
	fileStoragePath := flag.String("f", "", "FILE_STORAGE_PATH")

        flag.Parse()

	if len(serverAddress) > 0 {
		config.Server.ServerAddress = serverAddress
	}

	if len(baseURL) > 0 {
		config.Server.BaseURL = baseURL
	}

	if len(fileStoragePath) > 0 {
		config.FileStorage.FileStoragePath = fileStoragePath
	}

	return config
}
```

2022-02-28 17:06 UTC, Barugoo commented on config/config.go
> +func getFlags() (string, string, string) {
Я обратил внимание, что ты работаешь со структурой конфига по указателю, но при этом этот же указатель возвращаешь. Оба подхода имеют право на жизнь, только обычно ЛИБО мутируют объект по указателю, ЛИБО внутри функции создают копию изначального значение, делают что-то с ней и ее возвращают (встроенная функция append, например, так работает), оригинальное значение при этом остается прежним:
```go
func addNum(value *int, delta int) {
    *value += delta
}
```
Либо
```go
func addNum(value int, delta int) (newValue int) {
    return value+delta
}
```

2022-02-28 17:07 UTC, Barugoo commented on internal/app/domain/dto/longURL.go
> +func (longUrl *LongURL) SetValue(value string) {
Зачем здесь setter, если поле `Value` экспортируемое? Нам ничего не мешает изменять его напрямую=)

2022-02-28 17:09 UTC, Barugoo commented on internal/app/handlers/http/addJsonURLHandler.go
> +	url := h.URLMemoryService.GetURLByLongURLDto(longURLDto)
Несовсем понятно, что такое `Dto` 
Я бы посоветовал добавить комментарии ко всем экспортируемым функциям в проекте, чтобы код сам себя описывал

2022-02-28 17:10 UTC, Barugoo commented on internal/app/handlers/http/addJsonURLHandler.go
> +	shortURLJson, err := json.Marshal(h.URLMemoryService.GetShortURLDtoByURL(url))
Давай не будем здесь инлайнить:
```go
shortURL := h.URLMemoryService.GetShortURLDtoByURL(url)
shortURLJson, err := json.Marshal(shortURL)
if err != nil {
    	w.WriteHeader(http.StatusInternalServerError)
	return
}
```

2022-02-28 17:11 UTC, Barugoo commented on internal/app/handlers/http/addJsonURLHandler.go
> +	shortURLJson, err := json.Marshal(h.URLMemoryService.GetShortURLDtoByURL(url))
JSON - это аббревиатура, их в Go принято писать капсом

2022-02-28 17:11 UTC, Barugoo commented on internal/app/handlers/http/addJsonURLHandler.go
> +	w.Write([]byte(shortURLJson))
Я бы сделал вот так:
```go
shortURL := h.URLMemoryService.GetShortURLDtoByURL(url)
shortURLJson, err := json.NewEncoder(w).Encode(shortURL)
if err != nil {
    	w.WriteHeader(http.StatusInternalServerError)
	return
}

2022-02-28 17:15 UTC, Barugoo commented on internal/app/services/URLStorageService.go
> +	IsStorageExist() bool
Смотри, ты описываешь некий абстрактный интерфейс работы с хранилкой. Чаще всего работа с хранилкой - это i/o операция (запись/чтение с диска, запрос в базу и тд), а любая i/o операция может вернуть ошибку. Давай во всех методах вторым возвращаемым значением сделаем `error`

2022-02-28 17:15 UTC, Barugoo requested changes
Хорошо, но есть замечания

Спасибо, что подождал ревью

2022-03-03 13:52 UTC, PanovAlexey commented on internal/app/services/URLStorageService.go
> +	IsStorageExist() bool
Готово. В первых двух методах может вернуться ошибка. В третьем `IsStorageExist`  пока что просто проверка заполненного поля, поэтому возврат ошибки захардкодил как nil.

2022-03-03 13:52 UTC, PanovAlexey commented on internal/app/handlers/http/addJsonURLHandler.go
> +	w.Write([]byte(shortURLJson))
Проверку добавил.

2022-03-03 13:52 UTC, PanovAlexey commented on internal/app/handlers/http/addJsonURLHandler.go
> +	shortURLJson, err := json.Marshal(h.URLMemoryService.GetShortURLDtoByURL(url))
Готово.

2022-03-03 13:52 UTC, PanovAlexey commented on internal/app/handlers/http/addJsonURLHandler.go
> +	url := h.URLMemoryService.GetURLByLongURLDto(longURLDto)
Основной объект, который потом будет сохраняться в БД (а пока только в файл) - _type URL struct {}_
В нем содержится сразу и исходная ссылка (длинная) и сокращенная.

Но при этом в некоторых местах требуется формировать/передавать только исходную или только сокращенную ссылку. Поэтому, сделал для этих целей две DTOшки.

Добавил к ним описание.

2022-03-03 13:52 UTC, PanovAlexey commented on internal/app/domain/dto/longURL.go
> +func (longUrl *LongURL) SetValue(value string) {
Справедливо. Добавил и заюзал геттер.

2022-03-03 13:52 UTC, PanovAlexey commented on config/config.go
> +func getFlags() (string, string, string) {
Готово:
-  возвращаемые значения добавил
- две функции объединил в одну
- сигнатуру методов поправил - теперь конфиг передаю по значению

2022-03-03 13:52 UTC, PanovAlexey commented on cmd/shortener/main.go
> +	URLMemoryService.LoadURLs(URLStorageService.GetURLCollectionFromStorage())
Тут опасался, что в будущем накрутим функционал, появятся другие сервисы и начнем путаться.
Готово - названия сократил.

2022-03-03 13:52 UTC, PanovAlexey commented on cmd/shortener/main.go
> +		log.Printf("error creating file repository by config:" + error.Error())
Готово.

2022-03-03 13:52 UTC, PanovAlexey commented on cmd/shortener/main.go
> +	fileStorageRepository, error := repositories.GetFileStorageRepository(config)
Готово.

2022-03-03 15:51 UTC, PanovAlexey commented on internal/app/domain/dto/longURL.go
> +func (longUrl *LongURL) SetValue(value string) {
Эх, вернулся к варианту с экспортируемым полем и удалил геттер, т.к. данная структура принимает участие в сериализации.

2022-03-04 20:58 UTC, Barugoo commented on internal/app/domain/dto/longURL.go
> +func (longUrl *LongURL) SetValue(value string) {
SetValue нам получается теперь не нужна, разве нет?

2022-03-04 21:00 UTC, Barugoo commented on internal/app/repositories/FileStorageRepository.go
> +type FileStorageConfigInterface interface {
Я думаю, что интерфейс для конфига - это лишнее

2022-03-04 21:02 UTC, Barugoo commented on internal/app/services/URLMemoryService.go
> +}
Второе возвращаемое значение должно быть типа `error`, как я и писал в прошлом ревью. Здесь у тебя явно может произойти i/o => ошибка может быть и использующий этоот интерфейс код ее должен проверять

2022-03-04 21:02 UTC, Barugoo commented on internal/app/services/URLMemoryService.go
> +}
Опять же, не вижу смысла делать интерфейс для конфига

2022-03-05 04:32 UTC, PanovAlexey commented on internal/app/repositories/FileStorageRepository.go
> +type FileStorageConfigInterface interface {
Готово, заменил интерфейсы на прямую работу со структурой.

2022-03-05 04:32 UTC, PanovAlexey commented on internal/app/domain/dto/longURL.go
> +func (longUrl *LongURL) SetValue(value string) {
Точно. SetValue тоже упразднил.

2022-03-05 05:41 UTC, PanovAlexey commented on internal/app/services/URLMemoryService.go
> +}
Добавил второй параметр `error` на всякий случай. Правда, в методе `GetShortURLCode` просто работа со строками происходит. Вероятность возврата ошибки довольно мала.
А там, где работа с i/o осуществляется добавил возврат ошибок в рамках прошлой итерации .

2022-03-05 05:44 UTC, PanovAlexey commented on internal/app/services/URLMemoryService.go
> +}
Готово. От интерфейсов отказался.

2022-03-10 04:55 UTC, merged